# Generated by Django 3.2.5 on 2022-04-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('pess_nome', models.TextField(blank=True, db_column='pess_nome', default='', null=True, verbose_name='Nome')),
                ('pess_is_disponivel', models.BooleanField(db_column='pess_is_disponivel', default='True', verbose_name='Disponível')),
                ('pess_datetime_inclusao', models.DateTimeField(auto_now_add=True, db_column='pess_datetime_inclusao', max_length=250, null=True, verbose_name='Data/Hora Inclusão')),
                ('pess_datetime_alteracao', models.DateTimeField(auto_now=True, db_column='pess_datetime_alteracao', max_length=250, null=True, verbose_name='Data/Hora Alteração')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'db_table': 'pessoas',
                'permissions': (('list_pess', 'Listar Pessoas'),),
            },
        ),
    ]
