# Generated by Django 3.2.5 on 2022-04-25 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pess_fk_usuario_alteracao',
            field=models.ForeignKey(blank=True, db_column='pess_fk_usuario_alteracao', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_rel_usuario_alteracao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Alteração'),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='pess_fk_usuario_inclusao',
            field=models.ForeignKey(blank=True, db_column='pess_fk_usuario_inclusao', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_rel_usuario_inclusao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inclusão'),
        ),
    ]
